---
title: "RWorksheet_Suero#4a"
output: pdf_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r name, echo = TRUE}

#1 The table below shows the data about shoe size and height. Create a data frame.
df <- data.frame (Gender=c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M"),
                 
Shoe_Size=c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0),

Height=c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0))

df

# ------------

#a. 
# The data shows a coloumn for shoe size,a coloumn for height and a coloumn for gender
# With the corresponding values for each value. The data set has 28 data points with 3 Coloumns

# ------------

#b. 
females_subset <-df [df$Gender == "F", c("Gender", "Shoe_Size","Height")]
females_subset

males_subset <- df[df$Gender == "M", c("Gender", "Shoe_Size", "Height")]
males_subset

# ------------

#c.
mean_shoe_size <- mean(df$Shoe_Size)
mean_height <- mean(df$Height)

mean_shoe_size
mean_height

# ------------

#d. skip for now

# ------------

#2 
months_vector <- c("March","April","January","November","January",
                   "September","October","September","November","August",
                   "January","November","November","February","May","August",
                   "July","December","August","August","September","November","February",
                   "April")
factor_months_vector <- factor(months_vector)
factor_months_vector

# ------------

#3
summary(months_vector)
summary(factor_months_vector)
#The summary for "months_vector" provides information about the dataset's size, data type, and its most common value.

#Conversely, in the summary of "factor_months_vector," you can see how often each month appears.

#These summaries serve different purposes, offering insights into dataset characteristics and the distribution of categorical values as needed.

# ------------

#4
factorData <- c("East", "West", "North")
factor_frequency <- c(1,4,3)

newOrderdata <- factor(factorData,levels = c("East","West","North"))

print(newOrderdata)



# ------------

# 5

imported_table <- read.table(file ="/cloud/project/RWorksheet_Suero#4/import_march.csv", header = TRUE, sep = ",")
View(imported_table)



#------------

# 6

random_Num <- readline(prompt = "Enter number from 1 to 50: ")

random_Num <- as.numeric(random_Num)

paste("The number you have chosen is", random_Num)

if (random_Num > 50) {
  paste("The number selected is beyond the range of 1 to 50")
} else if (random_Num == 20) {
  paste("TRUE")
} else {
  paste(random_Num)
}

# ----------

#7

minimum_Bills <- function(price) {
  
  minBills <- price %/% 50
  paste("The minimum no. of bills:", minBills)
}

minimum_Bills(90)

# ----------

#8
# 8.a

names <- c("Annie", "Thea", "Steve", "Hanna")
grade1 <- c(85,65,75,95)
grade2 <- c(65,75,55,75)
grade3 <- c(85,90,80,100)
grade4 <- c(100,90,85,90)

grade <- data.frame(
  Name = names,
  Grade1 = grade1,
  Grade2 = grade2,
  Grade3 = grade3,
  Grade4 = grade4
)

grade

#8.b

math$Average <- (math$Grade1 + math$Grade2 + math$Grade3 + math$Grade4) / 4

highScores <- math[math$Average > 90,]
highScores

if (nrow(highScores) > 0) {
  paste(highScores$Name, "'s average grade this semester is", high_scorers$Average)
} else {
  paste("No students have an average math score over 90.")
}

# 8.c

first_Test <- sum(math$Grade1) / nrow(math)
first_Test

second_Test <- sum(math$Grade2) / nrow(math)
second_Test

third_Test <- sum(math$Grade3) / nrow(math)
third_Test

fourth_Test <- sum(math$Grade4) / nrow(math)
fourth_Test


if (first_Test < 80) {
  paste("The 1st test was difficult.")
} else if(second_Test < 80) {
  paste("The 2nd test was difficult.")
} else if(third_Test < 80) {
  paste("The 3rd test was difficult.")
} else if(fourth_Test < 80) {
  paste("The 4th test was difficult.")
} else {
  paste("No test had an average score less than 80.")
}

# 8.d
# Annie scores
if (mathScore[1,2] > mathScore[1,3] && mathScore[1,2] > mathScore[1,4] && mathScore[1,2] > mathScore[1,5]) {
  annieHighest <- mathScore[1,2]
} else if (mathScore[1,3] > mathScore[1,4] && mathScore[1,3] > mathScore[1,5]) {
  annieHighest <- mathScore[1,3]
} else if (mathScore[1,4] > mathScore[1,5] && mathScore[1,2] > mathScore[1,5]) {
  annieHighest <- mathScore[1,4]
} else {
  annieHighest <- mathScore[1,5]
}


# Thea scores
if (mathScore[2,2] > mathScore[2,3] && mathScore[2,2] > mathScore[2,4] && mathScore[2,2] > mathScore[2,5]) {
  theaHighest <- mathScore[2,2]
} else if (mathScore[2,3] > mathScore[2,4] && mathScore[2,3] > mathScore[2,5]) {
  theaHighest <- mathScore[2,3]
} else if (mathScore[2,4] > mathScore[2,5] && mathScore[2,2] > mathScore[2,5]) {
  theaHighest <- mathScore[2,4]
} else {
  theaHighest <- mathScore[2,5]
}

# Steve scores
if (mathScore[3,2] > mathScore[3,3] && mathScore[3,2] > mathScore[3,4] && mathScore[3,2] > mathScore[3,5]) {
  steveHighest <- mathScore[3,2]
} else if (mathScore[3,3] > mathScore[3,4] && mathScore[3,3] > mathScore[3,5]) {
  steveHighest <- mathScore[2,3]
} else if (mathScore[3,4] > mathScore[3,5] && mathScore[3,2] > mathScore[3,5]) {
  steveHighest <- mathScore[3,4]
} else {
  steveHighest <- mathScore[3,5]
}

# Hanna scores
if (mathScore[4,2] > mathScore[4,3] && mathScore[4,2] > mathScore[4,4] && mathScore[4,2] > mathScore[4,5]) {
  hannaHighest <- mathScore[4,2]
} else if (mathScore[4,3] > mathScore[4,4] && mathScore[4,3] > mathScore[4,5]) {
  hannaHighest <- mathScore[2,3]
} else if (mathScore[4,4] > mathScore[4,5] && mathScore[4,2] > mathScore[4,5]) {
  hannaHighest <- mathScore[4,4]
} else {
  hannaHighest <- mathScore[4,5]
}

mathScore$HighestGrades <- c(annieHighest, theaHighest, steveHighest, hannaHighest)


above90 <- mathScore[mathScore$HighestGrades > 90,]
above90

if (nrow(above90) > 0) {
  paste(above90$Name, "'s highest grade this semester is", above90$HighestGrade)
} else {
  paste("No students have an average math score over 90.")
}

```

